version: '3.8'

services:
  companyapi:
    build:
      context: ../CompanyAppAPI   
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=db;Database=CompanyDb;User Id=sa;Password=YourStrong!Passw0rd;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: companydb
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql  # Persist database data

  companyclient:
    build:
      context: ../CompanyAppClient 
      dockerfile: Dockerfile      
    ports:
      - "4200:80"
    depends_on:
      - companyapi
    environment:
      - ANGULAR_APP_API_URL=http://companyapi:5000
    working_dir: /app

volumes:
  sql_data:  # Persistent volume for database